server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # Static assets cache
  location ~* \.(?:css|js|woff2?|ttf|eot|svg|png|jpe?g|gif)$ {
    try_files $uri =404;
    expires 7d;
    access_log off;
  }

  # HTML5 history mode fallback for SPA
  location / {
    try_files $uri /index.html;
  }
}

